### ISSUE TITLE
Empty Screen in development environment

### ISSUE THREAD

**Issue by msaboor35** [opeolluwa/send-file#98]
I was looking to look at some issues in this repo but could not set up the development environment as I am unfamiliar with the frontend stack. Upon running `yarn tauri dev` I get the following screen.

![empty screen tauri](https://github.com/opeolluwa/send-file/assets/18523184/3d6be8fd-7d4b-4e2d-bc05-86dbd1653486)

Can you help me in setting up the dev environment?

My build Environment:
```yarn tauri info
yarn run v1.22.19
$ tauri info

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.20.0
  › npm: 8.19.4
  › pnpm: 8.6.1
  › yarn: 1.22.19
  › rustup: 1.26.0
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../out
  › devPath: http://localhost:1420/
  › framework: React (Next.js)
  › bundler: Vite

App directory structure
  ├─ public
  ├─ .vscode
  ├─ out
  ├─ .github
  ├─ src-tauri
  ├─ core
  ├─ screenshots
  ├─ .git
  ├─ src
  ├─ mobile
  ├─ node_modules
  └─ .next
Done in 11.13s.
```

**Comment by opeolluwa** [comment]
delete the `.next` and `out` directories. re-run the command `yarn tauri dev` when connected to the internet. This should fix it

**Comment by msaboor35** [comment]
I still observe the same behavior.

**Comment by msaboor35** [comment]
Thx for replying. I am working on the same repository on the dev branch.

**Comment by opeolluwa** [comment]
I believe the issue is fixed now, could you please verify that

**Comment by msaboor35** [comment]
I have updated my local branch but I am still seeing an empty page with a home icon as shown in the original post. I suspected that there might be some specific problem with my machine/environment. So I set up a new sample Tauri project (following steps from the Tauri quickstart) with the same stack/tooling (yarn, next) and it worked without any problems. I am not sure if I can provide more details as the dev tools console in the Tauri window does not give any warnings or errors. But I can tell that the typescript source code is loading in the window as we can see from the dev tools.

![image](https://github.com/opeolluwa/send-file/assets/18523184/a73e3734-22c2-4c7f-a0d8-2312d6237ac2)

If there is anything that I can set up or test in my environment, you can tell me. Thanks again for taking the time.

**Comment by opeolluwa** [comment]
did you update the fork or pulled the recent changes to your machine

**Comment by msaboor35** [comment]
Yes. I am up to date on the dev branch (commit [ed5880e4fa0c5c26a4b6f34729b0b0fd0eee82be](https://github.com/opeolluwa/send-file/commit/ed5880e4fa0c5c26a4b6f34729b0b0fd0eee82be)).

**Comment by opeolluwa** [comment]
could you fork the project, we'll try to debug the fork. I can't see to find what the error is and I'm not experiencing it anymore on my end

**Comment by msaboor35** [comment]
I created a fork of the master branch. Tried `yarn install` followed by `yarn tauri dev`. It showed the UI correctly. seems like I was not deleting the old artifacts (probably the .next folder) correctly. Thx for the help :)

**Comment by opeolluwa** [comment]
that's great!
